### ISSUE TITLE
Mads.display Does not know how to open image

### ISSUE THREAD

**Issue by finmod** [madsjulia/Mads.jl#10]
Running the contamination notebook in its entirety, the Mads.display commands give the following warning and no image:

Mads.plotmatches(md, forward_predictions, filename=rootname * "-w13a_w20a-init-match.svg", xtitle = "Time [a]", ytitle = "Concentration [ppb]")
Mads.display("w01-w13a_w20a-init-match.svg")

WARNING: Do not know how to open `w01-w13a_w20a-init-match.svg`

The same occurs for all other Mads.display() in contamination.jl

**Comment by montyvesselinov** [comment]
Mads.display() is tested on mac and unix. It may not work on Windows. It may require more work. If you know what command is needed to open SVG and PNG files in Windows I or you can add it in the code. In Julia, it should be something like: 

```
run(`open file.png`)
```
