### ISSUE TITLE
Warning: Package Mads : skipping update (dirty)....

### ISSUE THREAD

**Issue by finmod** [madsjulia/Mads.jl#11]
Starting a couple of days ago, the Windows Pkg.update() give the above warning for Mads. In addition Pkg.test("Mads") fails 

 "madsoutput"
 "madsservers"
 "madsup"
 "madswarn"
 "madswindows"
 "makearrayconditionalloglikelihood"
 "makearrayfunction"
 "makearrayloglikelihood"
 "makebigdt"
 "makebigdt!"
 "makecomputeconcentrations"
 "makedixonprice"
 "makedoublearrayfunction"
 "makelmfunctions"
 "makelocalsafunction"
 "makelogprior"
 "makemadscommandfunction"
 "makemadscommandfunctionandgradient"
 "makemadscommandgradient"
 "makemadsconditionalloglikelihood"
 "makemadsloglikelihood"
 "makemadsreusablefunction"
 "makemakearrayconditionalloglikelihood"
 "makepowell"
 "makerosenbrock"
 "makerotatedhyperellipsoid"
 "makesphere"
 "makesumsquares"
 "maxtorealmax!"
 "modelinformationcriteria"
 "modelruns"
 "modobsweights!"
 "modwellweights!"
 "montecarlo"
 "noplot"
 "obslineismatch"
 "of"
 "paramarray2dict"
 "paramdict2array"
 "parsemadsdata!"
 "parsenodenames"
 "partialof"
 "plotgrid"
 "plotmadsproblem"
 "plotmass"
 "plotmatches"
 "plotobsSAresults"
 "plotrobustnesscurves"
 "plotseries"
 "plotwellSAresults"
 "printSAresults"
 "printSAresults2"
 "pyyamlok"
 "quiet"
 "quietoff"
 "quieton"
 "readasciipredictions"
 "readjsonpredictions"
 "readobservations"
 "readyamlpredictions"
 "regexs2obs"
 "reload"
 "required"
 "resetmodelruns"
 "residuals"
 "reweighsamples"
 "rmdir"
 "rmfile"
 "rosenbrock"
 "runcmd"
 "runremote"
 "saltelli"
 "saltellibrute"
 "saltellibruteparallel"
 "saltelliparallel"
 "sampling"
 "savecalibrationresults"
 "savemadsfile"
 "savemcmcresults"
 "savesaltellirestart"
 "scatterplotsamples"
 "searchdir"
 "setallparamsoff!"
 "setallparamson!"
 "setdebuglevel"
 "setdefaultplotformat"
 "setdir"
 "setdynamicmodel"
 "setmadsinputfile"
 "setnewmadsfilename"
 "setobservationtargets!"
 "setobstime!"
 "setobsweights!"
 "setparamoff!"
 "setparamon!"
 "setparamsdistnormal!"
 "setparamsdistuniform!"
 "setparamsinit!"
 "setplotfileformat"
 "setprocs"
 "setseed"
 "settarget!"
 "settime!"
 "setverbositylevel"
 "setweight!"
 "setwellweights!"
 "showallparameters"
 "showobservations"
 "showparameters"
 "sinetransform"
 "sinetransformfunction"
 "sinetransformgradient"
 "spaghettiplot"
 "spaghettiplots"
 "sphericalcov"
 "sphericalvariogram"
 "sprintf"
 "status"
 "svrFeature"
 "svrOutput"
 "symlinkdir"
 "symlinkdirfiles"
 "tag"
 "test"
 "testj"
 "verbositylevel"
 "void2nan!"
 "weightedstats"
 "welloff!"
 "wellon!"
 "wells2observations!"
 "writeparameters"
 "writeparametersviatemplate"
 "yaml"                                 INFO: BIGUQ functions:
15-element Array{Any,1}:
 "BIGUQ"
 "BigDT"
 "BigOED"
 "dataframeresults"
 "dobigoed"
 "generateproposedobs"
 "getfailureprobabilities"
 "getmcmcchain"
 "getrobustness"
 "getrobustnesscurve"
 "inbox"
 "makebigdts"
 "makedecision"
 "makedecisionforproposedobs"
 "printresults"              INFO: Anasol functions:
22-element Array{Any,1}:
 "@code"
 "Anasol"
 "boundaryexpr"
 "boundarynames"
 "cinnerkernel"
 "dispersionnames"
 "dispersiontimedependenceexpr"
 "distributionexprs"
 "getboundaries"
 "getdispersions"
 "getinitdispersionfactor"
 "getsources"
 "inclosedinterval"
 "infinitedomainexpr"
 "innerkernel"
 "kernel"
 "maxnumberofdimensions"
 "quadgkwithtol"
 "retexpr"
 "sourcenames"
 "standardnormal"
 "symbolindex"                 INFO: ReusableFunctions functions:
3-element Array{Any,1}:
 "ReusableFunctions"
 "gethashfilename"
 "maker3function"   INFO: MetaProgTools functions:
7-element Array{Any,1}:
 "MetaProgTools"
 "getsymbols"
 "in"
 "populateexpression"
 "populateexpression!"
 "replacesymbol"
 "replacesymbol!"     INFO: RobustPmap functions:
4-element Array{Any,1}:
 "RobustPmap"
 "checkexceptions"
 "crpmap"
 "rpmap"          INFO: Mads functions:
1-element Array{Any,1}:
 "createmadsproblem"INFO: Mads functions:
1-element Array{Any,1}:
 "loadmadsfile" Volume in drive C is OS
 Volume Serial Number is 0C4C-9799

 Directory of C:\Users\Denis\.julia\v0.5\Mads

22-Dec-16  01:03 PM    <DIR>          .
22-Dec-16  01:03 PM    <DIR>          ..
10-Dec-16  06:40 PM             1,245 .gitignore
10-Dec-16  06:40 PM               546 .travis.yml
12-Oct-16  03:39 PM               357 ACKNOWLEDGMENTS.md
12-Oct-16  03:39 PM             1,446 COPYING.md
10-Dec-16  06:40 PM    <DIR>          deps
26-Dec-16  11:42 AM    <DIR>          docs
26-Dec-16  11:42 AM    <DIR>          examples
12-Oct-16  03:39 PM               554 EXAMPLES.md
12-Oct-16  03:39 PM               370 FUNCTIONS.md
12-Oct-16  03:39 PM             4,169 GETTING_STARTED.md
12-Oct-16  03:39 PM             1,614 INSTALLATION.md
12-Oct-16  03:39 PM            35,821 LICENSE
12-Oct-16  03:39 PM    <DIR>          logo
12-Oct-16  03:39 PM             1,975 MADS.md
23-Oct-16  10:05 AM             1,705 mkdocs.yml
12-Oct-16  03:39 PM             2,038 MODEL_COUPLING.md
12-Oct-16  03:39 PM             2,822 README.md
10-Dec-16  06:40 PM               291 REQUIRE
06-Nov-16  12:04 PM    <DIR>          scripts
10-Dec-16  06:40 PM    <DIR>          site
23-Dec-16  09:29 AM    <DIR>          src
10-Dec-16  06:40 PM    <DIR>          src-external
22-Dec-16  09:14 AM    <DIR>          src-interactive
20-Dec-16  05:13 PM    <DIR>          src-new
10-Dec-16  06:40 PM    <DIR>          src-old
07-Jan-17  11:46 AM    <DIR>          test
12-Oct-16  03:39 PM               597 TEST.md
              15 File(s)         55,550 bytes
              14 Dir(s)  223,631,298,560 bytes free
WARNING: 2017-01-07 11:46:45 Requested format (TIFF) is not acceptable! (PNG|PDF|PS|SVG)
WARNING: File `mads.png` is missing!
ERROR: LoadError: LoadError: MethodError: no method matching push!(::Gadfly.Guide.##86#91, ::Tuple{Array{Compose.Context,1},Int64})
Closest candidates are:
  push!(::Any, ::Any, ::Any) at abstractarray.jl:1715
  push!(::Any, ::Any, ::Any, ::Any...) at abstractarray.jl:1716
  push!(::Array{Any,1}, ::ANY) at array.jl:486
  ...
 in layout_guides(::Compose.Context, ::Gadfly.Coord.Cartesian, ::Gadfly.Theme, ::Gadfly.Guide.PositionedGuide, ::Vararg{Gadfly.Guide.PositionedGuide,N}) at C:\Users\Denis\.julia\v0.5\Gadfly\src\guide.jl:1119
 in #render_prepared#111(::Bool, ::Bool, ::Function, ::Gadfly.Plot, ::Gadfly.Coord.Cartesian, ::Gadfly.Aesthetics, ::Array{Gadfly.Aesthetics,1}, ::Array{Array{Gadfly.StatisticElement,1},1}, ::Array{Array{Gadfly.Aesthetics,1},1}, ::Array{Array{Gadfly.Data,1},1}, ::Dict{Symbol,Gadfly.ScaleElement}, ::Array{Gadfly.GuideElement,1}) at C:\Users\Denis\.julia\v0.5\Gadfly\src\Gadfly.jl:901
 in render_prepared(::Gadfly.Plot, ::Gadfly.Coord.Cartesian, ::Gadfly.Aesthetics, ::Array{Gadfly.Aesthetics,1}, ::Array{Array{Gadfly.StatisticElement,1},1}, ::Array{Array{Gadfly.Aesthetics,1},1}, ::Array{Array{Gadfly.Data,1},1}, ::Dict{Symbol,Gadfly.ScaleElement}, ::Array{Gadfly.GuideElement,1}) at C:\Users\Denis\.julia\v0.5\Gadfly\src\Gadfly.jl:875
 in render(::Gadfly.Plot) at C:\Users\Denis\.julia\v0.5\Gadfly\src\Gadfly.jl:821
 in copy!(::Array{Compose.Context,1}, ::Base.Generator{Tuple{Gadfly.Plot,Gadfly.Plot,Gadfly.Plot,Gadfly.Plot,Gadfly.Plot},Gadfly.#render}) at .\abstractarray.jl:477
 in _collect(::Type{Compose.Context}, ::Base.Generator{Tuple{Gadfly.Plot,Gadfly.Plot,Gadfly.Plot,Gadfly.Plot,Gadfly.Plot},Gadfly.#render}, ::Base.HasLength) at .\array.jl:250
 in vstack(::Gadfly.Plot, ::Gadfly.Plot, ::Gadfly.Plot, ::Gadfly.Plot, ::Vararg{Gadfly.Plot,N}) at C:\Users\Denis\.julia\v0.5\Gadfly\src\Gadfly.jl:946
 in #plotseries#296(::String, ::String, ::String, ::String, ::String, ::Bool, ::Function, ::Array{Float64,2}, ::String) at C:\Users\Denis\.julia\v0.5\Mads\src\MadsPlot.jl:969
 in (::Mads.#kw##plotseries)(::Array{Any,1}, ::Mads.#plotseries, ::Array{Float64,2}, ::String) at .\<missing>:0
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in process_options(::Base.JLOptions) at .\client.jl:262
 in _start() at .\client.jl:318
while loading C:\Users\Denis\.julia\v0.5\Mads\test\miscellaneous.jl, in expression starting on line 102
while loading C:\Users\Denis\.julia\v0.5\Mads\test\runtests.jl, in expression starting on line 7
================================[ ERROR: Mads ]=================================

failed process: Process(`'C:\Users\Denis\AppData\Local\Julia-0.5.0\bin\julia' -Cx86-64 '-JC:\Users\Denis\AppData\Local\Julia-0.5.0\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes 'C:\Users\Denis\.julia\v0.5\Mads\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================
ERROR: Mads had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at .\pkg\entry.jl:740
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at .\<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\pkg\dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258
 in test(::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258

julia>

**Comment by montyvesselinov** [comment]
Unfortunately, there are issues with Gadfly. I can test it further.

**Comment by finmod** [comment]
Gadfly is still throwing numerous flags. Any chance of closing this issue?

**Comment by montyvesselinov** [comment]
Can you try again? Please do Pkg.update(); also make sure that use the latest Gadfly. Note that Gadlfy does not work in julia v0.6. But everything should be fine under 0.5.

**Comment by finmod** [comment]
Success on WSL ubuntu 16.04 and Vbox ubuntu 16.04. This clearly depends on using the master version of Gadfly and making sure that Pkg.test("Gadfly") passes all tests. This can take a while to get right. I have had problems with cairo and pango libraries. In the end with Pkg.checkout("Gadfly"), Pkg.test("Mads") passes all tests. All of this is with Julia 0.5.1

The same approach on Windows succeeds with Pkg.test("Gadfly"). Instead Pkg.test("Mads") running with Administrator status fails with SVR. So far, I have not found a way to Pkg.build("SVR") successfully.

**Comment by montyvesselinov** [comment]
I made some changes in SVR. Please try it again. SVR uses libsvm 

https://www.csie.ntu.edu.tw/~cjlin/libsvm/

installation of libsvm needs g++

**Comment by montyvesselinov** [comment]
For Gadfly under Windows , you will need also to do 

Pkg.add("Cairo")
Pkg.add("Fontconfig")

Get the latest Mads (0.4.2) and hope it works now.

**Comment by finmod** [comment]
On Windows, almost there. This is the latest error report. There is a problem with file name:

Expression: Mads.getnextmadsfilename("a-v01.mads") == "./a-v03.mads"
   Evaluated: ".\\a-v03.mads" == "./a-v03.mads"
ERROR: LoadError: LoadError: There was an error during testing


---------------------------------------------------------------------
 "quietdefault"
 "quietoff"
 "quieton"
 "readasciipredictions"
 "readjsonpredictions"
 "readmodeloutput"
 "readobservations"
 "readyamlpredictions"
 "regexs2obs"
 "reload"
 "required"
 "resetmodelruns"
 "residuals"
 "restart"
 "restartoff"
 "restarton"
 "reweighsamples"
 "rmdir"
 "rmfile"
 "rosenbrock"
 "runcmd"
 "runremote"
 "saltelli"
 "saltellibrute"
 "saltellibruteparallel"
 "saltelliparallel"
 "sampling"
 "savecalibrationresults"
 "savemadsfile"
 "savemcmcresults"
 "savesaltellirestart"
 "scatterplotsamples"
 "searchdir"
 "setallparamsoff!"
 "setallparamson!"
 "setdebuglevel"
 "setdefaultplotformat"
 "setdir"
 "setdynamicmodel"
 "setmadsinputfile"
 "setmodelinputs"
 "setnewmadsfilename"
 "setobservationtargets!"
 "setobstime!"
 "setobsweights!"
 "setparamoff!"
 "setparamon!"
 "setparamsdistnormal!"
 "setparamsdistuniform!"
 "setparamsinit!"
 "setplotfileformat"
 "setprocs"
 "setseed"
 "settarget!"
 "settime!"
 "setverbositylevel"
 "setweight!"
 "setwellweights!"
 "showallparameters"
 "showobservations"
 "showparameters"
 "sinetransform"
 "sinetransformfunction"
 "sinetransformgradient"
 "spaghettiplot"
 "spaghettiplots"
 "sphericalcov"
 "sphericalvariogram"
 "sprintf"
 "status"
 "stdoutcaptureoff"
 "stdoutcaptureon"
 "svrFeature"
 "svrOutput"
 "symlinkdir"
 "symlinkdirfiles"
 "tag"
 "test"
 "testj"
 "transposematrix"
 "transposevector"
 "verbositylevel"
 "void2nan!"
 "weightedstats"
 "welloff!"
 "wellon!"
 "wells2observations!"
 "writeparameters"
 "writeparametersviatemplate"
 "yaml"                              INFO: Anasol functions:
22-element Array{Any,1}:
 "@code"
 "Anasol"
 "boundaryexpr"
 "boundarynames"
 "cinnerkernel"
 "dispersionnames"
 "dispersiontimedependenceexpr"
 "distributionexprs"
 "getboundaries"
 "getdispersions"
 "getinitdispersionfactor"
 "getsources"
 "inclosedinterval"
 "infinitedomainexpr"
 "innerkernel"
 "kernel"
 "maxnumberofdimensions"
 "quadgkwithtol"
 "retexpr"
 "sourcenames"
 "standardnormal"
 "symbolindex"                 INFO: AffineInvariantMCMC functions:
3-element Array{Any,1}:
 "AffineInvariantMCMC"
 "flattenmcmcarray"
 "sample"             INFO: GeostatInversion functions:
15-element Array{Any,1}:
 "FDDerivatives"
 "FFTRF"
 "GeostatInversion"
 "LowRankCovMatrix"
 "PCGALowRankMatrix"
 "RandMatFact"
 "getxis"
 "pcga"
 "pcgadirect"
 "pcgadirectiteration!"
 "pcgalsqr"
 "pcgalsqriteration"
 "randsvdwithseed"
 "rga"
 "srga"                INFO: BIGUQ functions:
15-element Array{Any,1}:
 "BIGUQ"
 "BigDT"
 "BigOED"
 "dataframeresults"
 "dobigoed"
 "generateproposedobs"
 "getfailureprobabilities"
 "getmcmcchain"
 "getrobustness"
 "getrobustnesscurve"
 "inbox"
 "makebigdts"
 "makedecision"
 "makedecisionforproposedobs"
 "printresults"              INFO: ReusableFunctions functions:
13-element Array{Any,1}:
 "ReusableFunctions"
 "checkfunctionkeywords"
 "checkhashfilename"
 "getfunctionkeywords"
 "gethashfilename"
 "loadresultfile"
 "maker3function"
 "quiet"
 "quietoff"
 "quieton"
 "resetrestarts"
 "restarts"
 "saveresultfile"       INFO: RobustPmap functions:
4-element Array{Any,1}:
 "RobustPmap"
 "checkexceptions"
 "crpmap"
 "rpmap"          INFO: MetaProgTools functions:
7-element Array{Any,1}:
 "MetaProgTools"
 "getsymbols"
 "in"
 "populateexpression"
 "populateexpression!"
 "replacesymbol"
 "replacesymbol!"     INFO: SVR functions:
16-element Array{Any,1}:
 "@cachedsym"
 "LINEAR"
 "POLY"
 "PRECOMPUTED"
 "RBF"
 "SIGMOID"
 "SVR"
 "freemodel"
 "liboutput"
 "mapnodes"
 "mapparam"
 "predict"
 "readlibsvmfile"
 "savemodel"
 "train"
 "verbosity"     INFO: Mads functions:
1-element Array{Any,1}:
 "createmadsproblem"INFO: Mads functions:
1-element Array{Any,1}:
 "loadmadsfile" Volume in drive C is OS
 Volume Serial Number is 0C4C-9799

 Directory of C:\Users\Denis\.julia\v0.5\Mads

28-Mar-17  06:31 PM    <DIR>          .
28-Mar-17  06:31 PM    <DIR>          ..
17-Mar-17  09:23 PM               187 .gitattributes
28-Mar-17  06:31 PM             1,248 .gitignore
17-Mar-17  09:23 PM             2,367 .gitlab-ci.yml
17-Mar-17  09:23 PM               537 .travis.yml
17-Mar-17  09:23 PM               357 ACKNOWLEDGMENTS.md
17-Mar-17  09:23 PM             1,446 COPYING.md
28-Mar-17  06:31 PM    <DIR>          deps
28-Mar-17  06:31 PM    <DIR>          docs
17-Mar-17  09:23 PM    <DIR>          examples
17-Mar-17  09:23 PM               634 EXAMPLES.md
17-Mar-17  09:23 PM               403 FUNCTIONS.md
17-Mar-17  09:23 PM             4,173 GETTING_STARTED.md
17-Mar-17  09:23 PM             1,644 INSTALLATION.md
17-Mar-17  09:23 PM            35,821 LICENSE
17-Mar-17  09:23 PM    <DIR>          logo
17-Mar-17  09:23 PM             2,125 MADS.md
28-Mar-17  06:31 PM             2,023 mkdocs.yml
17-Mar-17  09:23 PM             2,044 MODEL_COUPLING.md
17-Mar-17  09:23 PM    <DIR>          notebooks
17-Mar-17  09:23 PM             3,319 README.md
17-Mar-17  09:23 PM               373 REQUIRE
17-Mar-17  09:23 PM    <DIR>          scripts
28-Mar-17  06:31 PM    <DIR>          site
28-Mar-17  06:31 PM    <DIR>          src
18-Mar-17  11:45 AM    <DIR>          src-external
28-Mar-17  06:31 PM    <DIR>          src-interactive
24-Mar-17  11:53 PM    <DIR>          src-new
28-Mar-17  06:31 PM    <DIR>          src-old
31-Mar-17  01:54 PM    <DIR>          test
17-Mar-17  09:23 PM               609 TEST.md
              17 File(s)         59,310 bytes
              15 Dir(s)  200,662,986,752 bytes free
WARNING: 2017-03-31 13:54:30 Requested format (TIFF) is not acceptable! (PNG|PDF|PS|SVG)
WARNING: File `mads.png` is missing!
WARNING: Do not know how to open `test.png`
WARNING: 2017-03-31 13:54:58 Keyword already `ssdr` exists
INFO: Git status Mads ...
?? examples/anasol/mass_reduced.svg
?? examples/anasol/w01short-ax-2-spaghetti.svg
?? examples/anasol/w01short-match-w1a.svg
?? examples/anasol/w01short-match.svg
?? examples/anasol/w01short-vx-2-spaghetti.svg
?? test/finename_testing/
INFO: Git status Anasol ...
INFO: Git status AffineInvariantMCMC ...
INFO: Git status GeostatInversion ...
INFO: Git status BIGUQ ...
INFO: Git status ReusableFunctions ...
INFO: Git status RobustPmap ...
INFO: Git status MetaProgTools ...
INFO: Git status SVR ...
WARNING: Unknown parallel environment!
WARNING: No processors found to add!
INFO: Number of processors: 1 [1]
* io ...
* file naming ...
Test Failed
  Expression: Mads.getnextmadsfilename("a-v01.mads") == "./a-v03.mads"
   Evaluated: ".\\a-v03.mads" == "./a-v03.mads"
ERROR: LoadError: LoadError: There was an error during testing
 in record(::Base.Test.FallbackTestSet, ::Base.Test.Fail) at .\test.jl:397
 in do_test(::Base.Test.Returned, ::Expr) at .\test.jl:281
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in process_options(::Base.JLOptions) at .\client.jl:265
 in _start() at .\client.jl:321
while loading C:\Users\Denis\.julia\v0.5\Mads\test\filename.jl, in expression starting on line 8
while loading C:\Users\Denis\.julia\v0.5\Mads\test\runtests.jl, in expression starting on line 13
================================[ ERROR: Mads ]=================================

failed process: Process(`'C:\Users\Denis\AppData\Local\Julia-0.5.1\bin\julia' -Cx86-64 '-JC:\Users\Denis\AppData\Local\Julia-0.5.1\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes 'C:\Users\Denis\.julia\v0.5\Mads\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================
ERROR: Mads had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at .\pkg\entry.jl:749
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at .\<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\pkg\dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258
 in test(::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258

julia>

**Comment by montyvesselinov** [comment]
Thank you very much for checking on this. Modified version! pushed.

-monty
