### ISSUE TITLE
Extenion of Julia Mads to multivariate Gaussian priors and likelihood-informed parameter and state reduction

### ISSUE THREAD

**Issue by finmod** [madsjulia/Mads.jl#12]
Monty, 

Reading this work Scalable posterior approximations for large-scale Bayesian inverse ...https://arxiv.org/abs/1510.06053 by Cui, Marzouk and Willcox, can Julia Mads and in particular the calibrate module be extended to squared Hellinger distance in the data-misfit function, the likelihood-informed parameter subspace and likelihood-informed state reduction? Likelihood informed approaches appear in computational statistics but I see in this work that it is also used in geophysical applications as demonstrated in the groundwater aquifer inversion example which is close to the one you use in A Computationally Efficient.... and Mads examples.

**Comment by montyvesselinov** [comment]
No. We would with the MIT guys. But i think there method might be available soon at 

https://bitbucket.org/mituq/muq
