### ISSUE TITLE
Pkg.test("Mads") fails on both Windows and Ubuntu

### ISSUE THREAD

**Issue by finmod** [madsjulia/Mads.jl#13]
After a clean install of Julia v0.5 and Mads on both Windows and Ubuntu, Pkg.test("Mads") throws the error below. It would also be helpful to revise the READ.ME for specific instructions on both operating systems to have this standard Pkg.test("Mads") pass. In particular the requirement that the Julia window be Run as Administrator is not mentioned anywhere.

WARNING: deprecated syntax "call(::Type{ParetoFitnessScheme{N}}, ...)".
Use "(::Type{ParetoFitnessScheme{N}})(...)" instead.

WARNING: deprecated syntax "call(::Core.kwftype(Type{ParetoFitnessScheme{N}}), ...)".
Use "(::Core.kwftype(Type{ParetoFitnessScheme{N}}))(...)" instead.

WARNING: deprecated syntax "call(::Type{EpsDominanceFitnessScheme{N,F}}, ...)".
Use "(::Type{EpsDominanceFitnessScheme{N,F}})(...)" instead.

WARNING: deprecated syntax "call(::Core.kwftype(Type{EpsDominanceFitnessScheme{N,F}}), ...)".
Use "(::Core.kwftype(Type{EpsDominanceFitnessScheme{N,F}}))(...)" instead.

WARNING: deprecated syntax "call(::Type{EpsDominanceFitnessScheme{N}}, ...)".
Use "(::Type{EpsDominanceFitnessScheme{N}})(...)" instead.

WARNING: deprecated syntax "call(::Core.kwftype(Type{EpsDominanceFitnessScheme{N}}), ...)".
Use "(::Core.kwftype(Type{EpsDominanceFitnessScheme{N}}))(...)" instead.

WARNING: deprecated syntax "call(::Type{IndexedTupleFitness}, ...)".
Use "(::Type{IndexedTupleFitness})(...)" instead.

WARNING: deprecated syntax "call(::Type{IndexedTupleFitness}, ...)".
Use "(::Type{IndexedTupleFitness})(...)" instead.

WARNING: deprecated syntax "call(::Type{EpsBoxDominanceFitnessScheme{N,F}}, ...)".
Use "(::Type{EpsBoxDominanceFitnessScheme{N,F}})(...)" instead.

WARNING: deprecated syntax "call(::Core.kwftype(Type{EpsBoxDominanceFitnessScheme{N,F}}), ...)".
Use "(::Core.kwftype(Type{EpsBoxDominanceFitnessScheme{N,F}}))(...)" instead.

WARNING: deprecated syntax "call(::Type{EpsBoxDominanceFitnessScheme{N}}, ...)".
Use "(::Type{EpsBoxDominanceFitnessScheme{N}})(...)" instead.

WARNING: deprecated syntax "call(::Core.kwftype(Type{EpsBoxDominanceFitnessScheme{N}}), ...)".
Use "(::Core.kwftype(Type{EpsBoxDominanceFitnessScheme{N}}))(...)" instead.

WARNING: deprecated syntax "call(hc::HatCompare{FS}, ...)".
Use "(hc::HatCompare{FS})(...)" instead.

WARNING: deprecated syntax "call(::Type{FunctionBasedProblem}, ...)".
Use "(::Type{FunctionBasedProblem})(...)" instead.

WARNING: deprecated syntax "call(::Type{FunctionBasedProblem}, ...)".
Use "(::Type{FunctionBasedProblem})(...)" instead.
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\problem.jl:480
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\problem.jl:480
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\problem.jl:480

WARNING: deprecated syntax "call(::Type{TopListIndividual}, ...)".
Use "(::Type{TopListIndividual})(...)" instead.

WARNING: deprecated syntax "Base.(:(==))".
Use "Base.:(==)" instead.

WARNING: deprecated syntax "call(::Type{TopListArchive}, ...)".
Use "(::Type{TopListArchive})(...)" instead.

WARNING: deprecated syntax "call(::Type{TopListArchive}, ...)".
Use "(::Type{TopListArchive})(...)" instead.

WARNING: deprecated syntax "call(::Type{EpsBoxFrontierIndividual}, ...)".
Use "(::Type{EpsBoxFrontierIndividual})(...)" instead.

WARNING: deprecated syntax "call(::Type{EpsBoxArchive}, ...)".
Use "(::Type{EpsBoxArchive})(...)" instead.

WARNING: deprecated syntax "call(::Core.kwftype(Type{EpsBoxArchive}), ...)".
Use "(::Core.kwftype(Type{EpsBoxArchive}))(...)" instead.

WARNING: deprecated syntax "call(::Type{EpsBoxArchive}, ...)".
Use "(::Type{EpsBoxArchive})(...)" instead.

WARNING: deprecated syntax "call(::Type{EpsBoxArchiveFrontierIterator}, ...)".
Use "(::Type{EpsBoxArchiveFrontierIterator})(...)" instead.

WARNING: deprecated syntax "call(::Type{UniformMutation}, ...)".
Use "(::Type{UniformMutation})(...)" instead.

WARNING: deprecated syntax "call(::Type{MutationClock}, ...)".
Use "(::Type{MutationClock})(...)" instead.

WARNING: deprecated syntax "call(::Type{MutationClock}, ...)".
Use "(::Type{MutationClock})(...)" instead.

WARNING: deprecated syntax "call(::Type{PolynomialMutation}, ...)".
Use "(::Type{PolynomialMutation})(...)" instead.

WARNING: deprecated syntax "call(::Type{PolynomialMutation}, ...)".
Use "(::Type{PolynomialMutation})(...)" instead.

WARNING: deprecated syntax "call(::Type{PolynomialMutation}, ...)".
Use "(::Type{PolynomialMutation})(...)" instead.

WARNING: deprecated syntax "call(::Type{TournamentSelector}, ...)".
Use "(::Type{TournamentSelector})(...)" instead.

WARNING: deprecated syntax "call(::Type{TournamentSelector}, ...)".
Use "(::Type{TournamentSelector})(...)" instead.

WARNING: deprecated syntax "call(::Type{ProblemEvaluator}, ...)".
Use "(::Type{ProblemEvaluator})(...)" instead.

WARNING: deprecated syntax "call(::Type{ProblemEvaluator}, ...)".
Use "(::Type{ProblemEvaluator})(...)" instead.

WARNING: deprecated syntax "call(::Core.kwftype(Type{ProblemEvaluator}), ...)".
Use "(::Core.kwftype(Type{ProblemEvaluator}))(...)" instead.
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\random_search.jl:480

WARNING: deprecated syntax "call(::Type{DiffEvoOpt}, ...)".
Use "(::Type{DiffEvoOpt})(...)" instead.

WARNING: deprecated syntax "call(::Type{DiffEvoOpt}, ...)".
Use "(::Type{DiffEvoOpt})(...)" instead.

WARNING: deprecated syntax "call(::Type{DiffEvoOpt}, ...)".
Use "(::Type{DiffEvoOpt})(...)" instead.

WARNING: deprecated syntax "call(::Type{DiffEvoOpt}, ...)".
Use "(::Type{DiffEvoOpt})(...)" instead.
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\differential_evolution.jl:9
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\differential_evolution.jl:9
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\differential_evolution.jl:9
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\differential_evolution.jl:9
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\differential_evolution.jl:9
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\differential_evolution.jl:136
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\differential_evolution.jl:136
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\differential_evolution.jl:136
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\adaptive_differential_evolution.jl:74
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\adaptive_differential_evolution.jl:74
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\adaptive_differential_evolution.jl:74
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\resampling_memetic_search.jl:480
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\resampling_memetic_search.jl:480

WARNING: deprecated syntax "call(::Type{BorgMOEA}, ...)".
Use "(::Type{BorgMOEA})(...)" instead.

WARNING: deprecated syntax "call(::Type{BorgMOEA}, ...)".
Use "(::Type{BorgMOEA})(...)" instead.

WARNING: deprecated syntax "call(::Type{BorgMOEA}, ...)".
Use "(::Type{BorgMOEA})(...)" instead.

WARNING: deprecated syntax "call(::Type{BorgMOEA}, ...)".
Use "(::Type{BorgMOEA})(...)" instead.

WARNING: deprecated syntax "call(::Type{FunctionBasedProblemFamily}, ...)".
Use "(::Type{FunctionBasedProblemFamily})(...)" instead.

WARNING: deprecated syntax "call(::Type{FunctionBasedProblemFamily}, ...)".
Use "(::Type{FunctionBasedProblemFamily})(...)" instead.

WARNING: deprecated syntax "call(::Type{FunctionBasedProblemFamily}, ...)".
Use "(::Type{FunctionBasedProblemFamily})(...)" instead.
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\problems\problem_family.jl:480
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\problems\problem_family.jl:480
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\problems\problem_family.jl:480
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\problems\problem_family.jl:480
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\problems\problem_family.jl:64
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\problems\problem_family.jl:67
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\problems\problem_family.jl:70
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\problems\problem_family.jl:76

WARNING: deprecated syntax "call(::Type{MethodOutput}, ...)".
Use "(::Type{MethodOutput})(...)" instead.
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\optimization_result.jl:480
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\optimization_result.jl:480

WARNING: deprecated syntax "call(::Type{TopListArchiveOutput}, ...)".
Use "(::Type{TopListArchiveOutput})(...)" instead.

WARNING: deprecated syntax "call(::Type{ArchiveOutput}, ...)".
Use "(::Type{ArchiveOutput})(...)" instead.

WARNING: deprecated syntax "call(::Type{EpsBoxArchiveOutput}, ...)".
Use "(::Type{EpsBoxArchiveOutput})(...)" instead.

WARNING: deprecated syntax "call(::Type{ArchiveOutput}, ...)".
Use "(::Type{ArchiveOutput})(...)" instead.

WARNING: deprecated syntax "call(::Type{PopulationOptimizerOutput}, ...)".
Use "(::Type{PopulationOptimizerOutput})(...)" instead.

WARNING: deprecated syntax "call(::Type{MethodOutput}, ...)".
Use "(::Type{MethodOutput})(...)" instead.
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\opt_controller.jl:480
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\opt_controller.jl:480
WARNING: Base.UTF8String is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\problems\single_objective.jl:181

WARNING: deprecated syntax "call(::Type{Hypersurface}, ...)".
Use "(::Type{Hypersurface})(...)" instead.
WARNING: PkgDev is not available
WARNING: Ipopt is not available
ERROR: LoadError: LoadError: LoadError: UndefVarError: DefaultNLPSolver not defined
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in eval(::Module, ::Any) at .\boot.jl:234
 in require(::Symbol) at .\loading.jl:415
 in include_from_node1(::String) at .\loading.jl:488
 in process_options(::Base.JLOptions) at .\client.jl:262
 in _start() at .\client.jl:318
while loading C:\Users\Denis\.julia\v0.5\Mads\src\..\src-new\MadsInfoGap.jl, in expression starting on line 480
while loading C:\Users\Denis\.julia\v0.5\Mads\src\Mads.jl, in expression starting on line 151
while loading C:\Users\Denis\.julia\v0.5\Mads\test\runtests.jl, in expression starting on line 1
================================[ ERROR: Mads ]=================================

failed process: Process(`'C:\Users\Denis\AppData\Local\Julia-0.5.0\bin\julia' -Cx86-64 '-JC:\Users\Denis\AppData\Local\Julia-0.5.0\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes 'C:\Users\Denis\.julia\v0.5\Mads\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================
ERROR: Mads had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at .\pkg\entry.jl:740
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at .\<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\pkg\dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258
 in test(::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258

julia>

**Comment by montyvesselinov** [comment]
Sorry! we have removed the conflicting code. Hope it works now.
