### ISSUE TITLE
Ipopt Not Functioning 

### ISSUE THREAD

**Issue by jsschlosser** [madsjulia/Mads.jl#18]
Hello,

I get the following error after trying all troubleshooting methods. 
ERROR: UndefVarError: Ipopt not defined
 in #NMFipopt#240(::Int64, ::Float64, ::Bool, ::Int64, ::Int64, ::Array{Float64,2}, ::Array{Float64,2}, ::Int64, ::Bool, ::Mads.#NMFipopt, ::Array{Float64,2}, ::Int64) at C:\Users\Joseph\AppData\Local\JuliaPro-0.5.2.1\pkgs-0.5.2.1\v0.5\Mads\src\..\src-new\MadsBSS.jl:47
 in (::Mads.#kw##NMFipopt)(::Array{Any,1}, ::Mads.#NMFipopt, ::Array{Float64,2}, ::Int64) at .\<missing>:0

I looked into this and it seems to be not a bug in this package, but because Mads is doing unreliable things with conditional imports. I'm not sure how critical this is, but I figured I'd post it here.

Thank you,

Joe Schlosser

**Comment by montyvesselinov** [comment]
Ipopt is not required because the installation of Ipopt is problematic on
some LANL machines.

-monty

**Comment by jsschlosser** [comment]
I don't know what I did, but once I re-installed Julia it finally worked.
