### ISSUE TITLE
pycall/pyplot api updates

### ISSUE THREAD

**Issue by stevengj** [madsjulia/Mads.jl#23]
PyCall 1.90.0 and PyPlot 2.8.0 now released, which change `o[:foo]` and `o["foo"]` to `o.foo` and `o."foo"`, respectively, for python objects `o`; see also JuliaPy/PyCall.jl#629.

The old `getindex` methods still work but are deprecated, so you'll want to put out a new release that uses the new methods and REQUIREs the new versions to avoid having zillions of deprecation messages.

**Comment by montyvesselinov** [comment]
Resolved; Thank you very much!
