### ISSUE TITLE
Passing from Lora to Klara

### ISSUE THREAD

**Issue by scidom** [madsjulia/Mads.jl#4]
@montyvesselinov, Lora has been renamed to Klara (for historical reasons, referring to Klara von Neumann), so you may want to change "using Lora" to "using Klara" in Mads and BIGUQ (and to update the REQUIRE file by adding Klara 0.6.0 after removing Lora from it).

I tried to create a PR in Mads, but failed due to bad internet connection (I am in a remote island on holidays).

**Comment by montyvesselinov** [comment]
Thank you very much! Will do.
