### ISSUE TITLE
Running MadsExamples on initial install

### ISSUE THREAD

**Issue by finmod** [madsjulia/Mads.jl#6]
Trying to run MadsExamples in a ipynb with Julia 0.5 and Pkg.add("Mads") installed today, I get the following error:

WARNING: LMLin is not available
WARNING: symbol is deprecated, use Symbol instead.
 in depwarn(::String, ::Symbol) at .\deprecated.jl:64
 in symbol(::String, ::Vararg{String,N}) at .\deprecated.jl:30
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in eval(::Module, ::Any) at .\boot.jl:234
 in require(::Symbol) at .\loading.jl:415
 in include_from_node1(::String) at .\loading.jl:488
 in eval(::Module, ::Any) at .\boot.jl:234
 in require(::Symbol) at .\loading.jl:415
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in eval(::Module, ::Any) at .\boot.jl:234
 in require(::Symbol) at .\loading.jl:415
 in include_string(::String, ::String) at .\loading.jl:441
 in execute_request(::ZMQ.Socket, ::IJulia.Msg) at C:\Users\Denis.julia\v0.5\IJulia\src\execute_request.jl:169
 in eventloop(::ZMQ.Socket) at C:\Users\Denis.julia\v0.5\IJulia\src\eventloop.jl:8
 in (::IJulia.##9#15)() at .\task.jl:360
while loading C:\Users\Denis.julia\v0.5\ReverseDiffSource\src\tograph.jl, in expression starting on line 22
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\nstates/VariableNStates.jl:8
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\nstates/VariableNStates.jl:37
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\nstates/VariableNStates.jl:68
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\iostreams/VariableIOStreams.jl:77
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\iostreams/ParameterIOStreams/ParameterIOStreams.jl:21
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\variables/variables.jl:58
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\variables/variables.jl:76
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\variables/variables.jl:101
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\variables/variables.jl:125
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\variables/parameters/BasicDiscUnvParameter.jl:174
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\variables/parameters/BasicDiscMuvParameter.jl:176
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\variables/parameters/BasicContUnvParameter.jl:639
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\variables/parameters/BasicContMuvParameter.jl:653
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\models/GenericModel.jl:164
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\ranges/BasicMCRange.jl:38
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\tuners/VanillaMCTuner.jl:20
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\tuners/AcceptanceRateMCTuner.jl:51
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\tuners/DualAveragingMCTuner.jl:128
WARNING: Method definition (::Type{Klara.ARSState})(Klara.ParameterState{#S<:Distributions.ValueSupport, #F<:Distributions.VariateForm}, Klara.MCTunerState, Real, Real) in module Klara at C:\Users\Denis.julia\v0.5\Klara\src\samplers/ARS.jl:6 overwritten at C:\Users\Denis.julia\v0.5\Klara\src\samplers/ARS.jl:12.
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\samplers/ARS.jl:105
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\samplers/MH.jl:123
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\samplers/AM.jl:157
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\samplers/RAM.jl:208
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\samplers/HMC.jl:228
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\samplers/NUTS.jl:699
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\samplers/MALA.jl:122
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\samplers/SMMALA.jl:239
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\jobs/BasicMCJob.jl:374
WARNING: Base.writemime is deprecated.
  likely near C:\Users\Denis.julia\v0.5\Klara\src\jobs/BasicGibbsJob.jl:425
WARNING: Method definition mcvar_imse(AbstractArray, Any) in module Klara at C:\Users\Denis.julia\v0.5\Klara\src\stats/variance/mcvar.jl:103 overwritten at C:\Users\Denis.julia\v0.5\Klara\src\stats/variance/mcvar.jl:105.
WARNING: Method definition mcse_imse(AbstractArray, Any) in module Klara at C:\Users\Denis.julia\v0.5\Klara\src\stats/variance/mcvar.jl:118 overwritten at C:\Users\Denis.julia\v0.5\Klara\src\stats/variance/mcvar.jl:120.
WARNING: Method definition mcvar_ipse(AbstractArray, Any) in module Klara at C:\Users\Denis.julia\v0.5\Klara\src\stats/variance/mcvar.jl:160 overwritten at C:\Users\Denis.julia\v0.5\Klara\src\stats/variance/mcvar.jl:162.
WARNING: Method definition mcse_ipse(AbstractArray, Any) in module Klara at C:\Users\Denis.julia\v0.5\Klara\src\stats/variance/mcvar.jl:175 overwritten at C:\Users\Denis.julia\v0.5\Klara\src\stats/variance/mcvar.jl:177.
WARNING: Emcee is not available
WARNING: Method definition dobigoed(BIGUQ.BigOED, Real, Int64, Int64, Int64, Real) in module BIGUQ at C:\Users\Denis.julia\v0.5\BIGUQ\src\BIGOED.jl:139 overwritten at C:\Users\Denis.julia\v0.5\BIGUQ\src\BIGOED.jl:155.
INFO: Optimization ...
INFO: Optimization of Rosenbrock function ...
INFO: Nelder-Mead optimization (default) of the Rosenbrock function ...
INFO: Levenberg-Marquardt optimization in Optim module of the Rosenbrock function without sine transformation:
INFO: Sine transformation of parameter space ...
INFO: sine transformation:
INFO: Parameter transformation: [0.0,0.0] -> Mads.sinetransform(a, lowerbounds, upperbounds)
INFO: Parameter transformation: [1.5708,1.5708] -> Mads.sinetransform(a, lowerbounds, upperbounds)
INFO: Parameter transformation: [-1.5708,-1.5708] -> Mads.sinetransform(a, lowerbounds, upperbounds)
INFO: Parameter transformation in a function: [1.0,400.0] = Mads.rosenbrock_lm([2.0,2.0])
INFO: Parameter transformation in a function: [0.0,0.0] = Mads.rosenbrock_lm([1.0,1.0])
INFO: Levenberg-Marquardt optimization in Optim module of the Rosenbrock function with sine transformation:
INFO:  * Minimum back transformed: Mads.sinetransform(results.minimum, lowerbounds, upperbounds)
INFO: MADS Levenberg-Marquardt optimization of the Rosenbrock function without sine transformation:
WARNING: MultivariateOptimizationResults(method,initial_x,minimum,f_minimum,iterations,iteration_converged,x_converged,x_tol,f_converged,f_tol,g_converged,g_tol,trace,f_calls,g_calls) is deprecated, use MultivariateOptimizationResults(method,initial_x,minimum,f_minimum,iterations,iteration_converged,x_converged,x_tol,f_converged,f_tol,g_converged,g_tol,trace,f_calls,g_calls,0) instead.
 in depwarn(::String, ::Symbol) at .\deprecated.jl:64
 in Optim.MultivariateOptimizationResults{T,N,M}(::String, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64, ::Int64, ::Bool, ::Bool, ::Float64, ::Bool, ::Float64, ::Bool, ::Float64, ::Array{Optim.OptimizationState{Optim.LevenbergMarquardt},1}, ::Int64, ::Int64) at .\deprecated.jl:50
 in #levenberg_marquardt#126(::String, ::Float64, ::Float64, ::Float64, ::Int64, ::Int64, ::Int64, ::Float32, ::Float64, ::Float64, ::Int64, ::Int64, ::Bool, ::Bool, ::Mads.##131#137, ::Mads.#levenberg_marquardt, ::Mads.#rosenbrock_lm, ::Mads.#rosenbrock_gradient_lm, ::Array{Float64,1}, ::Mads.##130#136) at C:\Users\Denis.julia\v0.5\Mads\src\MadsLM.jl:521
 in (::Mads.#kw##levenberg_marquardt)(::Array{Any,1}, ::Mads.#levenberg_marquardt, ::Function, ::Function, ::Array{Float64,1}, ::Function) at .<missing>:0 (repeats 2 times)
 in include_from_node1(::String) at .\loading.jl:488
 in include_string(::String, ::String) at .\loading.jl:441
 in execute_request(::ZMQ.Socket, ::IJulia.Msg) at C:\Users\Denis.julia\v0.5\IJulia\src\execute_request.jl:169
 in eventloop(::ZMQ.Socket) at C:\Users\Denis.julia\v0.5\IJulia\src\eventloop.jl:8
 in (::IJulia.##9#15)() at .\task.jl:360
while loading C:\Users\Denis\Documents\Finmod\Mads.jl-master\examples\optimization\optimization_rosenbrock.jl, in expression starting on line 39
INFO: Levenberg-Marquardt optimization of an external problem using YAML files ...
LoadError: LoadError: MethodError: no method matching parsemadsdata(::String)
Closest candidates are:
  parsemadsdata(!Matched::Associative{K,V}) at C:\Users\Denis.julia\v0.5\Mads\src\MadsIO.jl:52
while loading C:\Users\Denis\Documents\Finmod\Mads.jl-master\examples\optimization\optimization_external_yaml_problem.jl, in expression starting on line 9
while loading In[1], in expression starting on line 7

 in #loadmadsfile#3(::Bool, ::String, ::Function, ::String) at C:\Users\Denis.julia\v0.5\Mads\src\MadsIO.jl:27
 in loadmadsfile(::String) at C:\Users\Denis.julia\v0.5\Mads\src\MadsIO.jl:22
 in include_from_node1(::String) at .\loading.jl:488

**Comment by montyvesselinov** [comment]
This issues is resolved in the latest version; please double check.
