### ISSUE TITLE
Precompile hangs in Julia 1.10.2

### ISSUE THREAD

**Issue by sonofwatt84** [madsjulia/Mads.jl#63]
I'm having trouble getting precompilation of Mads.jl to complete in a fresh install of Julia 1.10.2 on Ubuntu.

After several minutes of precompilation, CPU usage goes to down to minimal levels, but the process doesn't complete and appears to continue indefinitely.  Any advise or insight would be appreciated.

**Comment by montyvesselinov** [comment]
I have not tested it on Ubuntu recently. I will check it out tomorrow.

<https://envitrace.com/>

Velimir “monty” Vesselinov

Co-Founder & CTO - Envitrace

+1 505-473-4150

***@***.***> <https://calendly.com/montyv>
<https://github.com/montyvesselinov>
<https://www.linkedin.com/in/montyvesselinov> <https://montyv.github.io/>

**Comment by sonofwatt84** [comment]
Thanks!  It's Ubuntu 22.04.4 LTS running a 5.15 kernel if that's helpful.

**Comment by montyvesselinov** [comment]
I pushed changes. try the #master and let me know if works. I will commit
if all good. thank you! You may also try to run ] build Mads

<https://envitrace.com/>

Velimir “monty” Vesselinov

Co-Founder & CTO - Envitrace

+1 505-473-4150

***@***.***> <https://calendly.com/montyv>
<https://github.com/montyvesselinov>
<https://www.linkedin.com/in/montyvesselinov> <https://montyv.github.io/>

**Comment by sonofwatt84** [comment]
Unfortunately, I haven't seen much a change on my end with these changes...

**Comment by montyvesselinov** [comment]
If you try ] build Mads what do you get?

-monty

Velimir V Vesselinov
Co-Founder | CTO | CSO @ EnviTrace
+1 (505) 473 4150 | ***@***.*** | calendly | boomerang

**Comment by sonofwatt84** [comment]
Actually, that worked!  I get a library the precompiles and loads without issue!  Thank you so much!

**Comment by montyvesselinov** [comment]
Great!

<https://envitrace.com/>

Velimir “monty” Vesselinov

Co-Founder & CTO - Envitrace

+1 505-473-4150

***@***.***> <https://calendly.com/montyv>
<https://github.com/montyvesselinov>
<https://www.linkedin.com/in/montyvesselinov> <https://montyv.github.io/>

**Comment by orenbenkiki** [comment]
Running into the same problem. `build` works but the `precompile` hangs w/o consuming CPU. This happens even if I install the `master` revision. Running on MacOS 14.4.1 23E224 and Julia 1.10.2.

Side issue is that when trying to install the `master` revision I run into the "file too long" issue, even though I did `sudo git config --system core.longpaths true`. This happens in a symlink so I worked around it by `sudo git config --system core.symlinks false`. I hope I won't regret this later. Also, perhaps not using a symlink may have something to do with the precompile hanging? Since I also got the hanging when installing the published revision before I modified the git config, probably not?

Just having `build` work doesn't work around the problem - `use Mads` triggers the precompile which hangs :-(

Is there a workaround?

**Comment by montyvesselinov** [comment]
`Optim` fails. It is not our code. So we cannot do much about it. We may consider dropping it not fixed soon.

However, `Optim` errors do not prevent Mads from being executed and working with.

**Comment by orenbenkiki** [comment]
> Optim fails. It is not our code. So we cannot do much about it.

FWIW, `add Optim` works fine. This is something about an extension `OptimMOIExt` which is loaded in some fancy way (which seems to be recommended against)?

> We may consider dropping it not fixed soon.

If it is optional, the sooner the better - right now this makes it impossible for me to develop my computational pipeline.

> However, Optim errors do not prevent Mads from being executed and working with.

Great! Is there a way that `Optim` errors will not prevent _installing_ `Mads`?` Some way I can work around the pre-compile phase error?

**Comment by montyvesselinov** [comment]
`Optim` has been removed

**Comment by orenbenkiki** [comment]
Many thanks for the quick resolution!

**Comment by oktab1** [comment]
I could never get `Mads` to install on 1.10.2 on a fresh Ubuntu 22. What OS is recommended or what steps can I take to install it. I'm trying to install [GeoThermalCloud](https://github.com/SmartTensors/GeoThermalCloud.jl) but I keep getting stuck on `Mads`.

**Comment by montyvesselinov** [comment]
If you press Crtl-C, do you see an error message trail? Can you send it to
us?

Numerous users of Mads use it, and so far, there have not been issues with
the installation. We recently removed Optim, which was causing issues. I
guess, in your case, there might be issues related to some Python
dependencies that we are planning to remove. We are going to streamline the
code, remove many dependencies, and split it into several
independent packages.

Sorry about that.

<https://envitrace.com/>

Velimir “monty” Vesselinov

Co-Founder & CTO - Envitrace

+1 505-473-4150

***@***.***> <https://calendly.com/montyv>
<https://github.com/montyvesselinov>
<https://www.linkedin.com/in/montyvesselinov> <https://montyv.github.io/>

**Comment by oktab1** [comment]
@montyvesselinov, thanks for responding. On a fresh Ubuntu 20, below is the message trail after I pressed Ctrl-C.

```
        Info Packages marked with ⌃ and ⌅ have new versions available. Those with ⌃ may be upgradable, but those with ⌅ are restricted by compatibility constraints from upgrading. To see why use `status --outdated -m`
    Building Conda ─→ `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/51cab8e982c5b598eea9c8ceaced4b58d9dd37c9/build.log`
    Building PyCall → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/9816a3826b0ebf49ab4926e2b18842ad8b5c8f04/build.log`
    Building IJulia → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/47ac8cc196b81001a711f4b2c12c97372338f00c/build.log`
    Building Mads ──→ `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/ed907d655dd6b436c5fba73bedd53c4a261d7c60/build.log`
Precompiling project...
^C Interrupted: Exiting precompilation...===========>]  403/404
  ◑ Mads
  3 dependencies had output during precompilation:
┌ Mads
│      Updating registry at `~/.julia/registries/General.toml`
│     Resolving package versions...
│      Updating `~/.julia/environments/v1.10/Project.toml`
│    [c91e804a] + Gadfly v1.4.0
│    No Changes to `~/.julia/environments/v1.10/Manifest.toml`
│  Precompiling project...
│    ✓ LinearSolve → LinearSolveIterativeSolversExt
│      Mads Being precompiled by another process (pid: 4326, pidfile: /home/ubuntu/.julia/compiled/v1.10/Mads/P7IWT_LciJ0.ji.pidfile)
│  
│  [10694] signal (2): Interrupt
│  in expression starting at /home/ubuntu/.julia/packages/Mads/JBuSx/src/Mads.jl:143
│  epoll_wait at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
│  uv__io_poll at /workspace/srcdir/libuv/src/unix/epoll.c:236
│  uv_run at /workspace/srcdir/libuv/src/unix/core.c:400
│  ijl_task_get_next at /cache/build/builder-amdci5-1/julialang/julia-release-1-dot-10/src/partr.c:470
└  
┌ MKL_jll
│   Downloading artifact: MKL
│  
│  [pid 7590] waiting for IO to finish:
│   Handle type        uv_handle_t->data
│   timer              0xf0e700->0x7fb11574e7d0
│  This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.
│  
│  [pid 7590] waiting for IO to finish:
│   Handle type        uv_handle_t->data
│   timer              0xf0e700->0x7fb11574e7d0
│  This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.
└  
┌ Interpolations
│  WARNING: method definition for checkbounds at /home/ubuntu/.julia/packages/Interpolations/USkTk/src/Interpolations.jl:454 declares type variable N but does not use it.
│  WARNING: method definition for checkbounds at /home/ubuntu/.julia/packages/Interpolations/USkTk/src/Interpolations.jl:457 declares type variable N but does not use it.
│  WARNING: method definition for GriddedInterpolation at /home/ubuntu/.julia/packages/Interpolations/USkTk/src/gridded/gridded.jl:37 declares type variable pad but does not use it.
│  WARNING: method definition for GriddedInterpolation at /home/ubuntu/.julia/packages/Interpolations/USkTk/src/gridded/gridded.jl:60 declares type variable pad but does not use it.
│  WARNING: method definition for interpolate! at /home/ubuntu/.julia/packages/Interpolations/USkTk/src/deprecations.jl:30 declares type variable TWeights but does not use it.
└  

(@v1.10) pkg> 
```

**Comment by oktab1** [comment]
@montyvesselinov, did the message trail provide any insight into why I'm running into issues? Thanks!
