### ISSUE TITLE
DocumenterMarkdown

### ISSUE THREAD

**Issue by orenbenkiki** [madsjulia/Mads.jl#64]
The `MadsPublish.jl` imports `DocumenterMarkdown`, though it seems it doesn't use it. It generates the output in HTML format, which is already covered by `format=Documenter.Writers.HTMLWriter`; the `DocumentedMarkdown` allows generating Markdown output using `format=DocumenterMarkdown.Markdown`, which isn't used.

This wouldn't be a problem except that `DocumenterMarkdown` only works with pre-1.0 versions of `Documenter`, so installing `Mads` forces `Documenter` to an old version (0.27.25), which has an incompatible API with the 1.* `Documenter` versions, breaking anything that is using the latest (presumably stable?) `Documenter` 1.* API.

It also wouldn't have been a problem if `DocumenterMarkdown` was being updated, but according to https://github.com/JuliaDocs/DocumenterMarkdown.jl/issues/11 it doesn't seem like this would be any time soon.

How about simply removing `DocumenterMarkdown` as a dependency of `Mads`?

**Comment by asinghvi17** [comment]
FYI there is JuliaDocs/DocumenterMarkdown#13 which will transition DocumenterMarkdown to v1 of Documenter.  That should happen sometime this month.

**Comment by orenbenkiki** [comment]
Ugh, missed it (it wasn't linked by the issue). My bad.

Still - if `DocumenterMarkdown` isn't ever used, why make it a dependency and import it in the 1st place? Or am I missing something additional?

**Comment by montyvesselinov** [comment]
`DocumenterMarkdown` has been removed. I agree with your comments. We are working to compertamentalize the packages.
