### ISSUE TITLE
Parameter estimation, Bayesian approach to inverse problems in MADS

### ISSUE THREAD

**Issue by finmod** [madsjulia/Mads.jl#9]
A more interesting and substantial issue than running Mads on Windows! 
Can Mads/Julia deal with parameter estimation dealing with probabilitic measures for numerical solution of differential equations as in https://www2.warwick.ac.uk/fac/sci/statistics/staff/academic-research/girolami/probints/ ? The examples folder appears to be much broader than what is described in the docs. What is there in terms of parameter estimation? Do you have the LM for inverse modeling in there? Thanks

**Comment by montyvesselinov** [comment]
We do have LM for inverse analysis/parameter estimation. LM is our method of choice. However, it requires not a single objective function to minimize but a series of observations. The discrepancy between model predictions and observations is minimized (SSQR).

**Comment by finmod** [comment]
Even better the discrepancy between model predictions and observations. Is this the LIN ET AL.: PARALLEL LEVENBERG-MARQUARDT FOR INVERSE MODELING paper? Is it a minimum distance or a minimum variance discrepancy?

**Comment by montyvesselinov** [comment]
The implemented LM methodology is described at 

http://onlinelibrary.wiley.com/doi/10.1002/2016WR019028/full
